content:
  niche: "psychology_facts"
  video_length_minutes: 8
  videos_per_day: 3
  
voice:
  provider: "edge-tts"
  voice_name: "en-US-GuyNeural"
  speed: 1.1
  
images:
  count: 18
  style: "cinematic, professional, 4k, dramatic lighting"
  transition_duration: 0.5
  ken_burns: false
  
video:
  resolution: "1920x1080"
  fps: 30
  codec: "libx264"
  bitrate: "8M"
  background_music_volume: 0.2
  
youtube:
  category: 22
  language: "en"
  privacy: "public"
  made_for_kids: false
