name: Auto Generate YouTube Video

on:
  schedule:
    - cron: '35 5 * * *'  # Daily at 11 AM IST (5:30 AM UTC)
  workflow_dispatch:  # Manual trigger

jobs:
  generate:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
      
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Create .env file
        run: |
          echo "YOUTUBE_CLIENT_ID=${{ secrets.YOUTUBE_CLIENT_ID }}" >> .env
          echo "YOUTUBE_CLIENT_SECRET=${{ secrets.YOUTUBE_CLIENT_SECRET }}" >> .env
          echo "PEXELS_API_KEY=${{ secrets.PEXELS_API_KEY }}" >> .env
          echo "HUGGINGFACE_API_KEY=${{ secrets.HUGGINGFACE_API_KEY }}" >> .env
          echo "GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}" >> .env
          echo "CHANNEL_NAME=${{ secrets.CHANNEL_NAME }}" >> .env
      
      - name: Create client_secret.json
        run: |
          echo '${{ secrets.YOUTUBE_CLIENT_SECRET_JSON }}' > client_secret.json
      
      - name: Restore token.pickle
        uses: actions/cache@v3
        with:
          path: token.pickle
          key: youtube-token-${{ github.sha }}
          restore-keys: |
            youtube-token-
      
      - name: Generate and upload video
        run: |
          python main.py --mode single
      
      - name: Save token.pickle
        uses: actions/cache@v3
        with:
          path: token.pickle
          key: youtube-token-${{ github.sha }}
      
      - name: Upload artifacts
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: logs
          path: |
            automation.log
            logs/

# Setup Instructions:
# 1. Go to repository Settings > Secrets and variables > Actions
# 2. Add these secrets:
#    - YOUTUBE_CLIENT_ID: Your OAuth client ID
#    - YOUTUBE_CLIENT_SECRET: Your OAuth client secret
#    - YOUTUBE_CLIENT_SECRET_JSON: Full client_secret.json content
#    - PEXELS_API_KEY: Your Pexels API key
#    - HUGGINGFACE_API_KEY: Your Hugging Face API key (optional)
# 3. First run: Use workflow_dispatch to authenticate manually
# 4. After first run, token.pickle is cached for future runs
